config/routes.rb
Rails.application.routes.draw do
  get 'ingredient/name'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get "cocktails", to: "cocktails#index"
  # get "cocktails/new", to: "cocktails#new"
  # get "cocktails/:id", to:"cocktails#show", as: 'show'
  # post "cocktails", to: "cocktails#create", as: 'create'
  # get "cocktail/:id/edit", to: "cocktails#edit", as: 'edit'
  # patch "cocktails/:id", to: "cocktails#update", as: 'update'
  # delete "cocktails/:id", to: "cocktails#destroy", as: 'destroy'

  root to: 'cocktails#index'

  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
    has_many :cocktails, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end


  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [ :new, :create]

  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @dose = Dose.new(dose_params)
    @ingredient = Ingredient.find(dose_params[:ingredient_id])
    @dose.ingredient = @ingredient
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_dose
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/views/cocktails/_form.html.erb
<div class ="container">
  <div class="row">
    <div class="col-sm-offset-2 col-sm-10">
      <h2> Add Cocktail </h2>

      <%= simple_form_for(@cocktail) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      </div>

      <%= link_to "back to cocktails" , cocktails_path, class: 'btn btn-info'%>
      <%= f.submit class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<h1> edit page </h1>

<%= render "form" %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/greggstyle/image/upload/v1528466680/Mister%20Cocktail/kaizen-nguy-n-274069-unsplash.jpg');">
  <div class="banner-content">
    <h1>Cocktails</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/greggstyle/image/upload/v1528466680/Mister%20Cocktail/monika-grabkowska-636668-unsplash.jpg');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
            <%  if cocktail.doses != [ ] %>
            <h4><%= cocktail.doses.first.description %></h4>
            <h5><%= cocktail.doses.first.description %></h5>
            <% end %>
          </div>
          <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <br>
  <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-success btn-xs" %>
<!--       <%= link_to "all cocktails", cocktails_path, class: "btn btn-warning btn-xs" %>
-->

</div>

app/views/cocktails/new.html.erb
<%= render "form" %>

app/views/cocktails/show.html.erb
<div class ="container">
  <div class="row">
    <div class="col-sm-offset-2 col-sm-10">
      <h1 class: "h1"> Cocktails </h1>

      <h3> <%= @cocktail.name.upcase %> </h3>
      <ul>
      <% @cocktail.doses.each do |dose| %>
      <%= dose.ingredient.name %>
      <%= dose.description %>
      <%= link_to "", dose_path(dose),
      method: :delete,
      data: { confirm: "Are you sure?" } , class: "fa fa-trash"%>
      <% end %>
      <br>
      <br>
      <%= link_to "home", cocktails_path, class: 'btn btn-info'%>
      <%= link_to "add dose ", new_cocktail_dose_path(@cocktail), class: "btn btn-success " %>


      <%= link_to " delete", cocktail_path,
      method: :delete,
      data: { confirm: "Are you sure you want to delete cocktail?" } , class: "btn btn-danger" %>

    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<div class ="container">
  <div class="row">
    <div class="col-sm-offset-2 col-sm-10">
      <h1> Form Dose </h1>
      <h2> Add Dose for <%= @cocktail.name.upcase %></h2>
      <br>

      <%= simple_form_for([@cocktail, @dose]) do |f| %>
      <div class="form-group">
       <%= f.association :ingredient, collection: @ingredients %>
     </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: 3 %>
      </div>

     <%= link_to "back to cocktail", cocktails_path, class: 'btn btn-info'%>
     <%= f.submit class: 'btn btn-primary'%>

     <% end %>

   </div>
 </div>
</div>

app/views/doses/new.html.erb
<%= render "form" %>

app/views/ingredients/name.html.erb
<h1>Ingredient#name</h1>
<p>Find me in app/views/ingredient/name.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "shared/navbar" %>
  <%= yield %>
  <%= render "shared/footer" %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github-square"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-square"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-snapchat-square"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> by greggstyle
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "http://res.cloudinary.com/greggstyle/image/upload/v1528471034/logo_2.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Add cocktails", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Avatar with dropdown menu -->
   <!--  <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/greggstyle", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>